# Generated by Django 3.1.4 on 2020-12-29 19:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_contact_form_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateTimeField(auto_now_add=True)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=32)),
                ('address2', models.CharField(blank=True, max_length=32, null=True)),
                ('city', models.CharField(max_length=20)),
                ('county', models.CharField(blank=True, max_length=32, null=True)),
                ('postcode', models.CharField(blank=True, max_length=8, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('MEMBER', 'Member')], default='CANDIDATE', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
