# Generated by Django 3.1.4 on 2020-12-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_sizes_to_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
